export type Lang = "ru" | "en";

export const COPY = {
  ru: {
    kicker: "Симулятор вероятностей",
    title: "Лаборатория Монти Холла",
    lead: "Выбираешь дверь. Ведущий открывает пустую. Остаёшься или меняешь — частота побед не живёт в голове, она вылезает в результатах.",
    stay: "Остаться",
    switch: "Сменить",
    theory: "теория",
    games: "игр",
    doors: "Комнат",
    hostOpens: "Ведущий открывает пустых",
    pause: "Пауза",
    resume: "Дальше",
    reset: "Сброс",
    speed: "Скорость",
    last: "Последняя партия",
    pick: "выбор",
    prize: "приз",
    opened: "открыта",
    alt: "смена",
    whyTitle: "Почему процент сдвигается",
    whyBody:
      "Приз никуда не переезжает. Меняется информация: ведущий знает, где пусто, и намеренно открывает козу. Твоя первая дверь по-прежнему 1/n. Вся остальная вероятность схлопывается на неоткрытые чужие двери. Поэтому смена бьёт чаще, чем интуиция «теперь все равны».",
    formulaStay: "P(остаться) = 1 / n",
    formulaSwitch: "P(сменить) = (1 − 1/n) / (n − 1 − k)",
    formulaHint: "n — комнаты, k — сколько пустых открыл ведущий.",
    lang: "EN",
    footnote: "Открытый учебный проект. Частоты сходятся к формулам выше.",
  },
  en: {
    kicker: "Probability lab",
    title: "Monty Hall Lab",
    lead: "Pick a door. The host opens an empty one. Stay or switch — win rates are not a feeling. They show up in the long run.",
    stay: "Stay",
    switch: "Switch",
    theory: "theory",
    games: "trials",
    doors: "Rooms",
    hostOpens: "Host opens empty doors",
    pause: "Pause",
    resume: "Resume",
    reset: "Reset",
    speed: "Speed",
    last: "Last trial",
    pick: "pick",
    prize: "prize",
    opened: "open",
    alt: "switch",
    whyTitle: "Why the odds move",
    whyBody:
      "The prize never moves. Your information does: the host knows the empty doors and always opens a goat. Your first pick stays at 1/n. The leftover probability concentrates on the still-closed other doors. Switching beats the intuition that now they are equal.",
    formulaStay: "P(stay) = 1 / n",
    formulaSwitch: "P(switch) = (1 − 1/n) / (n − 1 − k)",
    formulaHint: "n is rooms, k is empty ones the host opens.",
    lang: "RU",
    footnote: "Open educational project. Empirical rates converge to the formulas above.",
  },
} as const;
